apiVersion: apps/v1
kind: Deployment
metadata:
  name: lost_island_backend
  labels:
    app: springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
        - name: springboot-app
          image: skull/lost_island_backend
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://10.0.0.1:3036/lost_island?serverTimezone=UTC&sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false&useSSL=false
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: 1234
          ports:
            - containerPort: 8080
            - containerPort: 9092
